url: https://teamnerd.github.io
baseurl: 
#/Portfolio-New/

# Site settings
title: TeamNerd
email: rlkorea@kakao.com
description: "Team Nerd for everyone"


# Team names, titles and social links
people:
- name: Alex
  pic: 1
  position: Deep Reinforcement Learning Engineer
  social:
    - title: github
      url: https://github.com/seolhokim

- name: Joongseok Kang
  pic: 2
  position: God
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/teamnerd

# Postal address (add as many lines as necessary)
address:
  - line: Seoul, Republic of Korea
  - line: # Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
